// File: lib/firebase_options.dart
// This file is generated by the FlutterFire CLI.
// It should not be modified manually unless you need to add configurations.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Correctly return the web configuration when the app is run on the web.
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCdTg_6cWfqkTiv4VJuhs3VovUQfpLBdw',
    appId: '1:627461571018:android:c000c9d300277cdeff8f33',
    messagingSenderId: '627461571018',
    projectId: 'news-ai-914981',
    storageBucket: 'news-ai-914981.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXQ6RbwCu1RbaeUFmZMzTRKjS5cy6FaMc',
    appId: '1:627461571018:ios:c2bad8239dadcb94ff8f33',
    messagingSenderId: '627461571018',
    projectId: 'news-ai-914981',
    storageBucket: 'news-ai-914981.firebasestorage.app',
    iosBundleId: 'com.unity.brevity',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCoyWR4pV-K6DKdCr8aj_NLqMFlwSRINlA",
    authDomain: "brevity-6c126.firebaseapp.com",
    projectId: "brevity-6c126",
    storageBucket: "brevity-6c126.firebasestorage.app",
    messagingSenderId: "590892472452",
    appId: "1:590892472452:web:2af85950367b92e0568ad1",
    measurementId: "G-1G17V3GELB",
  );
}